USE vendas_sucos;

CREATE TABLE tabela_de_vendas(
	NUMERO				VARCHAR(5) NOT NULL,
	DATA_VENDA			DATE NULL,
	CPF 				VARCHAR(11) NOT NULL,
	MATRICULA			VARCHAR(5) NOT NULL,
	IMPOSTO				FLOAT NULL,
	PRIMARY KEY (NUMERO)
);

ALTER TABLE tabela_de_vendas ADD CONSTRAINT fk_clientes FOREIGN KEY (cpf) REFERENCES clientes (cpf);

ALTER TABLE tabela_de_vendas ADD CONSTRAINT fk_vendedores FOREIGN KEY (matricula) REFERENCES vendedores (matricula);

ALTER TABLE itens_notas ADD CONSTRAINT fk_produtos FOREIGN KEY (codigo) REFERENCES produtos (codigo);

ALTER TABLE itens_notas ADD CONSTRAINT fk_notas FOREIGN KEY (numero) REFERENCES notas (numero);

-- lista as chaves estrangeiras de uma tabela
SELECT 
  TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
FROM
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  REFERENCED_TABLE_SCHEMA = 'vendas_sucos' AND
  REFERENCED_TABLE_NAME = 'notas';

 -- lista as chaves estrangeiras de uma coluna de tabela
SELECT 
  TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
FROM
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  REFERENCED_TABLE_SCHEMA = '<database>' AND
  REFERENCED_TABLE_NAME = '<table>' AND
  REFERENCED_COLUMN_NAME = '<column>';