-- seleciona o banco de dados
USE vendas_sucos;

-- comando sql de criação de tabela de produtos
CREATE TABLE produtos (
	CODIGO			VARCHAR(10) NOT NULL,
	DESCRITOR		VARCHAR(100) NULL,
	SABOR			VARCHAR(50) NULL,
	TAMANHO			VARCHAR(50) NULL,
	EMBALAGEM		VARCHAR(50) NULL,
	PRECO_LISTA		FLOAT NULL,
	PRIMARY KEY (CODIGO)
);

-- comando sql de criação de tabela de vendedores
CREATE TABLE vendedores (
	MATRICULA		VARCHAR(5) NOT NULL,
	NOME			VARCHAR(100) NULL,
	BAIRRO			VARCHAR(50) NULL,
	COMISSAO		FLOAT NULL,
	DATA_ADMISSAO	DATE NULL,
	FERIAS			BIT(1) NULL,
	PRIMARY KEY (MATRICULA)
);

-- comando sql de criação de tabela de clientes
CREATE TABLE clientes (
  CPF 				VARCHAR(11) NOT NULL,
  NOME 				VARCHAR(100) DEFAULT NULL,
  ENDERECO 			VARCHAR(150) DEFAULT NULL,
  BAIRRO 			VARCHAR(50) DEFAULT NULL,
  CIDADE 			VARCHAR(50) DEFAULT NULL,
  ESTADO 			VARCHAR(45) DEFAULT NULL,
  CEP 				VARCHAR(8) DEFAULT NULL,
  DATA_NASCIMENTO 	DATE DEFAULT NULL,
  IDADE 			INT(11) DEFAULT NULL,
  SEXO 				VARCHAR(1) DEFAULT NULL,
  LIMITE_CREDITO 	FLOAT DEFAULT NULL,
  VOLUME_COMPRA 	FLOAT DEFAULT NULL,
  PRIMEIRA_COMPRA 	BIT(1) DEFAULT NULL,
  PRIMARY KEY (CPF)
);

-- comando sql de criação de tabela de notas
CREATE TABLE notas (
	NUMERO			VARCHAR(5),
	DATA_VENDA		DATE,
	CPF				VARCHAR(11) NOT NULL,
	MATRICULA		VARCHAR(5) NOT NULL,
	IMPOSTO			FLOAT,
	PRIMARY KEY (NUMERO)
);

-- comando sql de criação de tabela de itens_notas
CREATE TABLE itens_notas (
	NUMERO			VARCHAR(5),
	CODIGO			VARCHAR(10) NOT NULL,
	QUANTIDADE		INT,
	PRECO			FLOAT,
	PRIMARY KEY (NUMERO)
);

SHOW TABLES;