USE vendas_sucos;

CREATE TABLE itens_notas (
	NUMERO		VARCHAR(5) NOT NULL,
	CODIGO		VARCHAR(10) NOT NULL,
	QUANTIDADE	INT,
	PRECO		FLOAT,
	PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE itens_notas ADD CONSTRAINT fk_notas FOREIGN KEY (NUMERO) REFERENCES notas (NUMERO);

ALTER TABLE itens_notas ADD CONSTRAINT fk_produtos FOREIGN KEY (codigo) REFERENCES produtos (codigo);