USE vendas_sucos;

SELECT * FROM notas;

SELECT * FROM itens_notas;

SELECT * FROM tb_faturamento;

UPDATE itens_notas SET QUANTIDADE = 200 WHERE NUMERO = '0104' AND CODIGO = '1002334';

DELETE FROM itens_notas WHERE NUMERO = '0104' AND CODIGO = '1002334';

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_UPDATE AFTER UPDATE ON itens_notas
FOR EACH ROW BEGIN
	DELETE FROM tb_faturamento;
	INSERT INTO tb_faturamento 
	SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA
		FROM notas A INNER JOIN itens_notas B ON A.NUMERO = B.NUMERO
		GROUP BY A.DATA_VENDA;
END//

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_DELETE AFTER DELETE ON itens_notas
FOR EACH ROW BEGIN
	DELETE FROM tb_faturamento;
	INSERT INTO tb_faturamento 
	SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA
		FROM notas A INNER JOIN itens_notas B ON A.NUMERO = B.NUMERO
		GROUP BY A.DATA_VENDA;
END//

DELIMITER ;


INSERT INTO notas(NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
	VALUES('0107', '2019-05-08', '1471156710', '235', 0.10);

INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
	VALUES('0107', '1000889', 100, 10);

INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
	VALUES('0107', '1002334', 100, 10);

SELECT * FROM notas;
SELECT * FROM itens_notas;

SELECT * FROM tb_faturamento;

UPDATE itens_notas SET QUANTIDADE = 200 WHERE NUMERO = '0107' AND CODIGO = '1002334';

DELETE FROM itens_notas WHERE NUMERO = '0107' AND CODIGO = '1002334';