# vale lembrar que cada comando deste neste arquivo gera uma nova layer na imagem final
FROM debian
LABEL maintainer 'Aluno Cod3r <aluno at cod3r.com.br>'

ARG S3_BUCKET=files
ENV S3_BUCKET=${S3_BUCKET}

