USE sucos_vendas;

SELECT * FROM notas_fiscais nf INNER JOIN itens_notas_fiscais inf ON nf.NUMERO = inf.NUMERO;

SELECT nf.CPF, nf.DATA_VENDA, inf.QUANTIDADE FROM notas_fiscais nf INNER JOIN itens_notas_fiscais inf ON nf.NUMERO = inf.NUMERO;

SELECT nf.CPF, DATE_FORMAT(nf.DATA_VENDA, '%Y-%m') AS MES_ANO, inf.QUANTIDADE
FROM notas_fiscais nf INNER JOIN itens_notas_fiscais inf ON nf.NUMERO = inf.NUMERO;

/* consulta com vendas de clientes por mês */
SELECT nf.CPF, DATE_FORMAT(nf.DATA_VENDA, '%Y-%m') AS MES_ANO, SUM(inf.QUANTIDADE) AS QUANTIDADE_VENDAS
FROM notas_fiscais nf INNER JOIN itens_notas_fiscais inf ON nf.NUMERO = inf.NUMERO
GROUP BY nf.CPF, DATE_FORMAT(nf.DATA_VENDA, '%Y-%m');

/* limite de compra por cliente */
SELECT * FROM tabela_de_clientes tc;

SELECT tc.CPF, tc.NOME, tc.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE FROM tabela_de_clientes tc;

SELECT x.CPF, x.NOME, x.MES_ANO, x.QUANTIDADE_VENDAS ,x.QUANTIDADE_LIMITE,
x.QUANTIDADE_LIMITE - x.QUANTIDADE_VENDAS AS DIFERENCA
	FROM (
	SELECT nf.CPF, tc.NOME,
		DATE_FORMAT(nf.DATA_VENDA, '%Y-%m') AS MES_ANO,
		SUM(inf.QUANTIDADE) AS QUANTIDADE_VENDAS,
		MIN(tc.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE
	FROM notas_fiscais nf
		INNER JOIN itens_notas_fiscais inf ON nf.NUMERO = inf.NUMERO
		INNER JOIN tabela_de_clientes tc ON nf.CPF = tc.CPF
	GROUP BY nf.CPF, DATE_FORMAT(nf.DATA_VENDA, '%Y-%m'), tc.NOME
	) x;


SELECT x.CPF, x.NOME, x.MES_ANO, x.QUANTIDADE_VENDAS ,x.QUANTIDADE_LIMITE,
x.QUANTIDADE_LIMITE - x.QUANTIDADE_VENDAS AS DIFERENCA,
CASE WHEN (x.QUANTIDADE_LIMITE - x.QUANTIDADE_VENDAS) < 0 THEN 'INVALIDA'
ELSE 'VALIDA'
END AS STATUS
	FROM (
	SELECT nf.CPF, tc.NOME,
		DATE_FORMAT(nf.DATA_VENDA, '%Y-%m') AS MES_ANO,
		SUM(inf.QUANTIDADE) AS QUANTIDADE_VENDAS,
		MIN(tc.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE
	FROM notas_fiscais nf
		INNER JOIN itens_notas_fiscais inf ON nf.NUMERO = inf.NUMERO
		INNER JOIN tabela_de_clientes tc ON nf.CPF = tc.CPF
	GROUP BY nf.CPF, DATE_FORMAT(nf.DATA_VENDA, '%Y-%m'), tc.NOME
	) x; 


SELECT x.CPF, x.NOME, x.MES_ANO, x.QUANTIDADE_VENDAS,
x.QUANTIDADE_LIMITE, ROUND(1 - (x.QUANTIDADE_LIMITE /x.QUANTIDADE_VENDAS) * 100, 2) AS PERCENTUAL,
CASE WHEN (x.QUANTIDADE_LIMITE - x.QUANTIDADE_VENDAS) < 0 THEN 'INVALIDA'
ELSE 'VALIDA'
END AS STATUS
	FROM (
	SELECT nf.CPF, tc.NOME,
		DATE_FORMAT(nf.DATA_VENDA, '%Y-%m') AS MES_ANO,
		SUM(inf.QUANTIDADE) AS QUANTIDADE_VENDAS,
		MIN(tc.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE
	FROM notas_fiscais nf
		INNER JOIN itens_notas_fiscais inf ON nf.NUMERO = inf.NUMERO
		INNER JOIN tabela_de_clientes tc ON nf.CPF = tc.CPF
	GROUP BY nf.CPF, DATE_FORMAT(nf.DATA_VENDA, '%Y-%m'), tc.NOME
	) x
	WHERE (x.QUANTIDADE_LIMITE - x.QUANTIDADE_VENDAS) < 0;