USE sucos_vendas;

SELECT CURRENT_TIMESTAMP() AS DATA_E_HORA FROM dual; 

SELECT CONCAT('O dia de hoje é ', CURRENT_TIMESTAMP()) AS MENSAGEM FROM dual;

SELECT CONCAT('O dia de hoje é ', DATE_FORMAT(CURRENT_TIMESTAMP(), '%W, %d/%m/%Y - %U')) AS MENSAGEM
	FROM dual;
	
SELECT SUBSTRING(CONVERT(23.3, CHAR), 1, 1) AS CARACTER FROM dual;