USE sucos_vendas;

SELECT tp.SABOR, nf.DATA_VENDA, inf.QUANTIDADE
	FROM tabela_de_produtos tp
	INNER JOIN itens_notas_fiscais inf ON tp.CODIGO_DO_PRODUTO = inf.CODIGO_DO_PRODUTO
	INNER JOIN notas_fiscais nf ON inf.NUMERO = nf.NUMERO;

-- quantidade vendida por sabor ano 2016
SELECT tp.SABOR, YEAR(nf.DATA_VENDA) AS ANO, SUM(inf.QUANTIDADE) AS QUANTIDADE
	FROM tabela_de_produtos tp
	INNER JOIN itens_notas_fiscais inf ON tp.CODIGO_DO_PRODUTO = inf.CODIGO_DO_PRODUTO
	INNER JOIN notas_fiscais nf ON inf.NUMERO = nf.NUMERO
	WHERE YEAR(nf.DATA_VENDA) = 2016
	GROUP BY tp.SABOR, YEAR(nf.DATA_VENDA)
	ORDER BY SUM(inf.QUANTIDADE) DESC;

SELECT YEAR(nf.DATA_VENDA) AS ANO, SUM(inf.QUANTIDADE) AS QUANTIDADE
	FROM tabela_de_produtos tp
	INNER JOIN itens_notas_fiscais inf ON tp.CODIGO_DO_PRODUTO = inf.CODIGO_DO_PRODUTO
	INNER JOIN notas_fiscais nf ON inf.NUMERO = nf.NUMERO
	WHERE YEAR(nf.DATA_VENDA) = 2016
	GROUP BY YEAR(nf.DATA_VENDA)
	ORDER BY SUM(inf.QUANTIDADE) DESC;
	
SELECT * FROM
(SELECT tp.SABOR, YEAR(nf.DATA_VENDA) AS ANO, SUM(inf.QUANTIDADE) AS QUANTIDADE
	FROM tabela_de_produtos tp
	INNER JOIN itens_notas_fiscais inf ON tp.CODIGO_DO_PRODUTO = inf.CODIGO_DO_PRODUTO
	INNER JOIN notas_fiscais nf ON inf.NUMERO = nf.NUMERO
	WHERE YEAR(nf.DATA_VENDA) = 2016
	GROUP BY tp.SABOR, YEAR(nf.DATA_VENDA)) AS VENDA_SABOR
INNER JOIN 
(SELECT YEAR(nf.DATA_VENDA) AS ANO, SUM(inf.QUANTIDADE) AS TOTAL
	FROM tabela_de_produtos tp
	INNER JOIN itens_notas_fiscais inf ON tp.CODIGO_DO_PRODUTO = inf.CODIGO_DO_PRODUTO
	INNER JOIN notas_fiscais nf ON inf.NUMERO = nf.NUMERO
	WHERE YEAR(nf.DATA_VENDA) = 2016
	GROUP BY YEAR(nf.DATA_VENDA)) AS VENDA_TOTAL
ON VENDA_SABOR.ANO = VENDA_TOTAL.ANO

SELECT VENDA_SABOR.SABOR, VENDA_SABOR.ANO, VENDA_SABOR.QUANTIDADE,
ROUND((VENDA_SABOR.QUANTIDADE/VENDA_TOTAL.TOTAL) * 100, 2) AS PARTICIPACAO FROM
(SELECT tp.SABOR, YEAR(nf.DATA_VENDA) AS ANO, SUM(inf.QUANTIDADE) AS QUANTIDADE
	FROM tabela_de_produtos tp
	INNER JOIN itens_notas_fiscais inf ON tp.CODIGO_DO_PRODUTO = inf.CODIGO_DO_PRODUTO
	INNER JOIN notas_fiscais nf ON inf.NUMERO = nf.NUMERO
	WHERE YEAR(nf.DATA_VENDA) = 2016
	GROUP BY tp.SABOR, YEAR(nf.DATA_VENDA)) AS VENDA_SABOR
INNER JOIN 
(SELECT YEAR(nf.DATA_VENDA) AS ANO, SUM(inf.QUANTIDADE) AS TOTAL
	FROM tabela_de_produtos tp
	INNER JOIN itens_notas_fiscais inf ON tp.CODIGO_DO_PRODUTO = inf.CODIGO_DO_PRODUTO
	INNER JOIN notas_fiscais nf ON inf.NUMERO = nf.NUMERO
	WHERE YEAR(nf.DATA_VENDA) = 2016
	GROUP BY YEAR(nf.DATA_VENDA)) AS VENDA_TOTAL
ON VENDA_SABOR.ANO = VENDA_TOTAL.ANO
ORDER BY VENDA_SABOR.QUANTIDADE DESC;